<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-15T23:13:38 IST" name="Default suite" finished-at="2021-08-15T23:13:38 IST" duration-ms="54">
    <groups>
    </groups>
    <test started-at="2021-08-15T23:13:38 IST" name="Default test" finished-at="2021-08-15T23:13:38 IST" duration-ms="54">
      <class name="TestCalc">
        <test-method signature="init()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="init" finished-at="2021-08-15T23:13:38 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="test1emptystring()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test1emptystring" finished-at="2021-08-15T23:13:38 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1emptystring -->
        <test-method signature="test2returnsinglevalue()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test2returnsinglevalue" finished-at="2021-08-15T23:13:38 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2returnsinglevalue -->
        <test-method signature="test3returnsumoftwoinput()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test3returnsumoftwoinput" finished-at="2021-08-15T23:13:38 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3returnsumoftwoinput -->
        <test-method signature="test4returnssumwithnewlinedelimiter()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test4returnssumwithnewlinedelimiter" finished-at="2021-08-15T23:13:38 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4returnssumwithnewlinedelimiter -->
        <test-method signature="test5threenumsum()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test5threenumsum" finished-at="2021-08-15T23:13:38 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5threenumsum -->
        <test-method signature="test6throwsexceptionfornegativeinputs()[pri:0, instance:TestCalc@6dbb137d]" started-at="2021-08-15T23:13:38 IST" name="test6throwsexceptionfornegativeinputs" finished-at="2021-08-15T23:13:38 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestCalc.test6throwsexceptionfornegativeinputs()[pri:0, instance:TestCalc@6dbb137d] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestCalc.test6throwsexceptionfornegativeinputs()[pri:0, instance:TestCalc@6dbb137d] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6throwsexceptionfornegativeinputs -->
      </class> <!-- TestCalc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
