<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="8" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-15T23:26:08 IST" name="Default suite" finished-at="2021-08-15T23:26:08 IST" duration-ms="53">
    <groups>
    </groups>
    <test started-at="2021-08-15T23:26:08 IST" name="Default test" finished-at="2021-08-15T23:26:08 IST" duration-ms="53">
      <class name="TestCalc">
        <test-method signature="init()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="init" finished-at="2021-08-15T23:26:08 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="test1emptystring()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test1emptystring" finished-at="2021-08-15T23:26:08 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1emptystring -->
        <test-method signature="test2returnsinglevalue()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test2returnsinglevalue" finished-at="2021-08-15T23:26:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2returnsinglevalue -->
        <test-method signature="test3returnsumoftwoinput()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test3returnsumoftwoinput" finished-at="2021-08-15T23:26:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3returnsumoftwoinput -->
        <test-method signature="test4returnssumwithnewlinedelimiter()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test4returnssumwithnewlinedelimiter" finished-at="2021-08-15T23:26:08 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4returnssumwithnewlinedelimiter -->
        <test-method signature="test5threenumsum()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test5threenumsum" finished-at="2021-08-15T23:26:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5threenumsum -->
        <test-method signature="test6throwsexceptionfornegativeinputs()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test6throwsexceptionfornegativeinputs" finished-at="2021-08-15T23:26:08 IST" duration-ms="1" status="PASS">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Negatives not allowed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Negatives not allowed
at Calculator.checkfornegativeinputs(Calculator.java:22)
at Calculator.add(Calculator.java:29)
at Calculator.calculate(Calculator.java:15)
at TestCalc.test6throwsexceptionfornegativeinputs(TestCalc.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6throwsexceptionfornegativeinputs -->
        <test-method signature="test7ignorenumbergreaterthan1000()[pri:0, instance:TestCalc@2f112965]" started-at="2021-08-15T23:26:08 IST" name="test7ignorenumbergreaterthan1000" finished-at="2021-08-15T23:26:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7ignorenumbergreaterthan1000 -->
      </class> <!-- TestCalc -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
